In [1]:
import numpy as np

## 1

In [2]:
np.__version__

'1.19.5'

In [4]:
n = int(input('Enter number of elements in the list '))
l = []
for i in range(0, n):
    l.append(int(input('Enter next ')))
l = np.array(l)
arr1, arr2 = np.unique(l, return_counts = True)
for i, j in zip(arr1, arr2):
    print(i, " appears ", j, " times")

Enter number of elements in the list 6
Enter next 1
Enter next 2
Enter next 1
Enter next 4
Enter next 2
Enter next 1
1  appears  3  times
2  appears  2  times
4  appears  1  times


## 2

In [5]:
l = list(input('Enter a binary number '))
l = np.array(l)
l.sort()
("").join(list(l))[::-1]

Enter a binary number 1110011


'1111100'

## 3

In [6]:
s = input('Enter a string ')
n = int(input('Enter index to remove '))
l = list(s)
l = l[0:n] + l[n+1:]
print(("").join(l))

Enter a string Hello Hi Bonjour
Enter index to remove 7
Hello H Bonjour


## 4

In [7]:
arr = np.ones(shape = (3, 3))
arr1 = np.zeros(shape = (1, 3))
arr2 = np.zeros(shape = (5, 1))
arr3 = np.r_[arr1, arr, arr1]
arr4 = np.c_[arr2, arr3, arr2]
print(arr4)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## 5

In [8]:
a1 = np.array([0, 10, 20, 40, 60])
a2 = np.array([0, 40])
a3 = []
for i in a1:
    a3.append(bool(np.isin(i, a2)))
a3

[True, False, False, True, False]

## 6

In [9]:
a1 = np.array([0, 10, 20, 40, 60, 80])
a2 = np.array([10, 30, 40, 50, 70])
a3 = [i for i in np.union1d(a1, a2) if i not in np.intersect1d(a1, a2)]
a3

[0, 20, 30, 50, 60, 70, 80]

## 7

In [10]:
a1 = np.array([0, 10, 20, 40, 60])
a2 = np.array([10, 30, 40, 50, 70])
a3 = np.column_stack((a1, a2))
a3

array([[ 0, 10],
       [10, 30],
       [20, 40],
       [40, 50],
       [60, 70]])

## 8

In [11]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print('Rank ', np.linalg.matrix_rank(matrix))
print('Trace ', np.trace(matrix))
print('Determinant ', np.linalg.det(matrix))

Rank  2
Trace  34
Determinant  0.0
